plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-navigation
  
baseurl: "/md"
url: "https://xly1981.github.io"

title: SH_ROBOT的网站
description: FROM IT TO AI.
twitter:
  username: Sh_robot

navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/
